name: tests

on: [push, pull_request]

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.0, 8.1]

        name: P${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, exif
                  coverage: none

            - name: Install dependencies
              run: |
                  composer update --prefer-dist --no-interaction
                  
            - name: Execute tests
              run: composer test
